// eslint-disable-next-line import/no-anonymous-default-export
export default {
  SET_COMMUTATORS: "SET_COMMUTATORS",
  FILTER_COMMUTATORS: "FILTER_COMMUTATORS",
  SET_COMMUTATORS_STATUS: "SET_COMMUTATORS_STATUS",
  SET_COMMUTATOR_CURRENT: "SET_COMMUTATOR_CURRENT",
  SET_COMMUTATOR_MESSAGES: "SET_COMMUTATOR_MESSAGES",
  SET_DOP_INFO: "SET_DOP_INFO",
  FETCHING: "FETCHING",
  MAIN_INFO: "MAIN_INFO",
  FULL_COMMUTATOR_INFO: "FULL_COMMUTATOR_INFO",
  OPEN_ALL_COMMUTATORS: "OPEN_ALL_COMMUTATORS",
  CHANGE_OPEN_COMMUTATOR: "CHANGE_OPEN_COMMUTATOR",
};
