// eslint-disable-next-line import/no-anonymous-default-export
export default {
	SET_SYNC: "SET_SYNC",
	FETCHING: "FETCHING",
	CURRENT_SYNC_INFO: "CURRENT_SYNC_INFO",
	FILTER_CURRENT_INFO: "FILTER_CURRENT_INFO",
	FILTER_ONE: "FILTER_ONE",
	FILTER_PERIOD: "FILTER_PERIOD",
	FILTER_PLANNED: "FILTER_PLANNED",
  DELETE_ALL_IMMEDIATE: "DELETE_ALL_IMMEDIATE",
  DELETE_ALL_PERIODIC: "DELETE_ALL_PERIODIC",
  DELETE_ALL_SCHEDULED: "DELETE_ALL_SCHEDULED"
};
